### ISSUE TITLE
Using in Pycharm

### ISSUE THREAD

**Issue by Vponed** [currentsapi/extractnet#3] opened 2022-01-18 22:53 UTC
I fight for two days, I pumped out a few gigabytes of info, but I could not get the library to work. All the time dependency errors.
 Do you have any instructions on how to install the library in Pycharm?

**Comment by Vponed** [comment] 2022-01-19 03:10
> I fight for two days, I pumped out a few gigabytes of info, but I could not get the library to work. All the time dependency errors. Do you have any instructions on how to install the library in Pycharm?

Resolved:
conda create -n extractnet python=3.8
conda activate extractnet
pip install extractnet

**Comment by theblackcat102** [comment] 2022-05-03 01:06
Hi @Vponed the issue should be resolved in the latest 2.0.4 version. The root cause was a installation problem

**Closed by theblackcat102** 2022-05-03 01:06 UTC
